[package]
name = "rfb-pixelbuffer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rfb-common = { workspace = true }
rfb-protocol = { workspace = true }
anyhow = { workspace = true }
